/// <reference path='../../_all.ts' />

module dashboard {
    'use strict';

    export class ServiceProviderDetailItem {
        constructor(
            public assertionConsumerServiceUrl: string,
            public wantAuthnRequestSigned: boolean,
            public signSAMLResponse: boolean,
            public signAssertion: boolean,
            public encryptAssertion: boolean,
            public assertionLifeTime: string,

            public disableInboundLogout: boolean,
            public disableOutboundLogout: boolean,
            public disableInResponseToCheck: boolean,
            public disablePendingLogoutCheck: boolean,
            public signLogoutRequest: boolean,
            public signLogoutResponse: boolean,
            public wantLogoutRequestSigned: boolean,
            public wantLogoutResponseSigned: boolean,
            public useEmbeddedCertificate: boolean,
            public issuerFormat: string,
            public nameIDFormat: string,
            public digestMethod: string,
            public signatureMethod: string,
            public wantDigestMethod: string,
            public wantSignatureMethod: string,
            public keyEncryptionMethod: string,
            public dataEncryptionMethod: string,
            public disableDestinationCheck: boolean,
            public logoutRequestLifeTime: string,
            public singleLogoutServiceBinding: string,
            public singleLogoutServiceResponseUrl: string,
            public partnerCertificateFile: string,
            public partnerCertificateSerialNumber: string,
            public partnerCertificateThumbprint: string,
            public partnerCertificateSubject: string,
            public secondaryPartnerCertificateFile: string,
            public secondaryPartnerCertificateSerialNumber: string,
            public clockSkew: string,
            public secondaryPartnerCertificateThumbprint: string,
            public tertiaryPartnerCertificateFile: string,
            public tertiaryPartnerCertificateSerialNumber: string,
            public tertiaryPartnerCertificateThumbprint: string,
            public tertiaryPartnerCertificateSubject: string,
            public singleLogoutServiceUrl: string,
            public secondaryPartnerCertificateSubject: string,
            public authnContext: string,

            public tertiaryLocalCertificateThumbprint: string,
            public tertiaryLocalCertificateSerialNumber: string,
            public tertiaryLocalCertificatePasswordKey: string,
            public tertiaryLocalCertificatePassword: string,
            public tertiaryLocalCertificateFile: string,
            public secondaryLocalCertificateSubject: string,
            public secondaryLocalCertificateThumbprint: string,
            public secondaryLocalCertificateSerialNumber: string,
            public secondaryLocalCertificatePasswordKey: string,
            public secondaryLocalCertificatePassword: string,
            public secondaryLocalCertificateFile: string,
            public localCertificateSubject: string,
            public localCertificateThumbprint: string,
            public localCertificateSerialNumber: string,
            public localCertificatePasswordKey: string,
            public localCertificatePassword: string,
            public localCertificateFile: string,
            public description: string,
            public name: string,
            public tertiaryLocalCertificateSubject: string
        ) {}
    }
}
