//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEFront.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISEFront.App_GlobalResources.content", typeof(content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Norwegian BankID brick or mobile.
        /// </summary>
        public static string BankIDDescription {
            get {
                return ResourceManager.GetString("BankIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankID.
        /// </summary>
        public static string BankIDTitle {
            get {
                return ResourceManager.GetString("BankIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an electronic ID.
        /// </summary>
        public static string ChooseAnElectronicID {
            get {
                return ResourceManager.GetString("ChooseAnElectronicID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to access the guest wireless network of Conscia AS Norge. Before you continue, it is required by the corporate policy of Conscia AS as well as current EU and Norwegian regulation to identify yourself through secure means before gaining access to this network..
        /// </summary>
        public static string LoginPortalMessage {
            get {
                return ResourceManager.GetString("LoginPortalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Access Portal.
        /// </summary>
        public static string LoginPortalTitle {
            get {
                return ResourceManager.GetString("LoginPortalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Norwegian MinID code from SMS or card.
        /// </summary>
        public static string MinIDDescription {
            get {
                return ResourceManager.GetString("MinIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinID.
        /// </summary>
        public static string MinIDTitle {
            get {
                return ResourceManager.GetString("MinIDTitle", resourceCulture);
            }
        }
    }
}
